name: flutter_reanimated
description: A animated project.
version: 1.0.0+1
repository: https://github.com/Nghi-NV/flutter_reanimated.git

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
